name: Continuous Integration
on: 
  push:
  pull_request:
    branches:
     - master
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            qt_arch: win32_msvc2019
            os_short: win
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare short commit sha
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Configure build for x86
        if: startsWith(runner.os, 'Windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          arch: ${{ matrix.qt_arch }}
          aqtversion: '>=1.2.1'
          py7zrversion: '>=0.16.1'

      - name: Configure
        run: qmake SourceAdminTool.pro -config release
        
      - name: Build Windows
        if: startsWith(runner.os, 'Windows')
        run: | 
          nmake
          windeployqt --no-compiler-runtime --no-opengl-sw --no-system-d3d-compiler --no-translations --no-angle --dir package release/SourceAdminTool.exe
          Copy-Item GeoLite2-Country.mmdb,app_list_map.ini,commands.xml,release\SourceAdminTool.exe -Destination package -PassThru

      - name: Create archive
        uses: actions/upload-artifact@v2
        with:
          name: SAT-${{ matrix.os_short }}-${{ env.GITHUB_SHA_SHORT }}
          path: package
